### ISSUE TITLE
Hide Recommended Looks Cropped and Weird

### ISSUE THREAD

**Issue by ghost** [hereafter/power-start-menu#19]
![Screenshot 2023-04-22 183819](https://user-images.githubusercontent.com/7698035/233798841-ae87a412-c96a-4e93-9565-21b91a83a691.png)

When I first downloaded this tool the feature worked totally fine but as of the past week the "hide recommended" feature has started pushing the search bar in the start menu up, causing it to look cropped and weird

**Comment by ghost** [comment]
![Screenshot 2023-04-22 183819](https://user-images.githubusercontent.com/7698035/233798920-315e6133-5fd9-47ba-93dd-ee705c624dbb.png)

This is the spacing with the feature disabled

**Comment by hereafter** [comment]
This is to maximize the area for the pinned items, so we could have one more line of pinned items.

![image](https://user-images.githubusercontent.com/1483954/233799488-0ec84db7-83b2-449e-9f42-fa967e5fd83d.png)


You may try "hide searchbox" to see if it is ok, since typing any characters will bring the seach panel anyway.

Meanwhile I am able to reproduce the look On OS 22621, I will see if  I could bring the search box down to make the top and bottom gaps balanced. 

Thanks for reporting

**Comment by hereafter** [comment]
Please kindly wait for 1.6 release, after upgrade it will look like

![image](https://user-images.githubusercontent.com/1483954/233826611-c24d9e2f-0bc8-43b0-a3e3-7efea13ba0e5.png)

**Comment by ghost** [comment]
awesome, thank you!
